name: boco
description: BOCO es una app que facilita la adopciÃ³n responsable de mascotas, conecta a los usuarios con lugares pet-friendly, brinda consejos de cuidado animal y permite gestionar el bienestar de sus mascotas con una lista de actividades personalizadas.

version: 7.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI and Design
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17

  # Utilities
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  fonts:
    - family: OrganicBrand
      fonts:
        - asset: assets/fonts/OrganicBrand.ttf
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Medium.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700

  assets:
    - assets/images/icono-boco.png
    - assets/images/perfil BOCO.png
    - assets/icons/icono-google.svg